name: Scan GitHub Repositories and build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Console Output
        run: .\.scripts\Write-Log.ps1
        shell: pwsh